import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../styles/Home.module.css";

const Verify: NextPage = (props: any) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h5>{props.message}</h5>
				<h1 className={styles.title}>
					Welcome to <a href="">Smart Trading Bot</a>
				</h1>
				<span className={styles.image}>
					<Image src="/robot.png" alt="Vercel Logo" width={200} height={220} />
				</span>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};
export const getServerSideProps = async (context: any) => {
	const token = context.query.token;
	const res = await fetch(
		`${process.env.HOST}/api/v1/user/verify/${token}`
	);

	 const rsl = await res.json();
	
	return {
		props: {
			message: rsl.message,
		},
	};
};
export default Verify;
